### ISSUE TITLE
Manter dados do usuário após refresh da página

### ISSUE THREAD

**Issue by llucasrgt** [conteumconto/dashboard#7]
Quando logado no sistema, o usuário recebe um token que é armazenafo no localStorage, o que faz com que quando recarregado a página não o perca.

Porém os dados do usuário em si estão sendo armazenados somente com o Vuex, o que faz com que estes dados sejam perdidos quando efetuado um refresh.

A dúvida é se é correto manter os dados do usuário em localStorage para não perdê-los ou redirecionar para tela de login caso um refresh seja efetuado?

**Comment by davikawasaki** [comment]
Existem várias formas de você guardar dados de forma temporária do acesso do usuário: cookies, localStorage, sessionStorage, services... Cada uma delas têm suas vantagens e desvantagens, então não tem uma maneira correta de guardar os dados do usuário.

Existem certas leis - como a EU Cookie Law - que questiona a permissão de você guardar os dados do usuário sem a permissão dele. Mas aplicações do mercado guardam mesmo assim, mas alternam entre cookies e localStorage.

Enfim, o jeito menos pior é guardar em localStorage dados que possam ultrapassar 4kb (limite máximo dos cookies), já que o mesmo aceita até 5mb. Se forem dados sensíveis, você criptografa e guarda lá, mas de qualquer forma vai ter que criptografar toda vez que precisar acessar aqueles dados. Você pode até guardar os dados em serviços - classes de implementação - que no caso do AngularJS são os services/factories/providers, mas não são práticas tão usadas no mercado.

Outra sugestão é usar o sessionStorage para guardar as informações de login do usuário - como o token JWT e todas as variáveis de autenticação - já que essas informações são limpas se o usuário fechar a aba ou o navegador.

**Final Thoughts on Local Storage and Security
1. Don't use local storage for session identifiers. Stick with cookies and use the HTTPOnly and Secure flags.
2. If cookies won't work for some reason, then use session storage which will be cleared when the user closes the browser window.
3. Be cautious with storing sensitive data in local storage. Just like any other client side storage options this data can be viewed and modified by the user.** 

Se quiserem essas leituras falam mais a respeito:
http://michael-coates.blogspot.com.br/2010/07/html5-local-storage-and-xss.html
http://dreamdealer.nl/articles/localstorage_vs_cookies_vs_the_law.html
https://auth0.com/blog/cookies-vs-tokens-definitive-guide/
http://blog.thiagobelem.net/armazenando-informacoes-no-computador-do-visitante-com-localstorage-e-sessionstorage
